name: rehab_hub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sudoku_solver_generator: ^2.1.0+1
  quiver: ^3.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/shapes/
    - assets/animal/
